language: c

script: asdf plugin-test helm https://github.com/virtualstaticvoid/asdf-helm.git

before_script:
  - git clone --branch v0.5.1 https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

os:
  - linux
